[package]
name = "common"
version = "0.1.0"
authors = ["scipi <scipii48@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.0"
serde = "1.0.118"
bson = "1.1.0"
sha3 = "0.9.1"
base64 = "0.13.0"
hex-literal = "0.3.1"
rand = "0.8.0"
